<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
	public function count()
	{
		$dql = "SELECT count(c.id) AS people FROM AppBundle:Customer c";
		$result = $this->getEntityManager()->createQuery($dql)->getScalarResult();
		return $result[0]['people'];
	}

	public function mostPopularFirstnames()
	{
		$em = $this->getEntityManager();
		$rsm = new ResultSetMapping;
		$rsm->addEntityResult('AppBundle:Customer', 'c');
		$rsm->addScalarResult('firstname', 'firstname');
		$rsm->addScalarResult('people', 'people');
		$query = $em->createNativeQuery('SELECT c.firstname, COUNT(c.id) AS people FROM customers c GROUP BY c.firstname ORDER BY people DESC LIMIT 10', $rsm);
		return $query->getResult();
	}

}
